---
terracotta/terracotta-3.7.5.tar.gz:
  object_id: 3cb26400-f6f0-4fe2-be13-39cbfa1d9cfb
  sha: !binary |-
    N2Q5YTk3MWY2NDA5Y2MwMjExNDFjMjFmN2E1MWE0MjY0MWRhZjFhYw==
  size: 62254931
java/jre-7u4-linux-x64.tar.gz:
  object_id: 4c73eb0a-8fc6-4144-a47b-6b061f3c7dd7
  sha: !binary |-
    MTEwOGQxNzQ0YmFhNzNiZjZjYWEyYWRmOTY1ZDBmNDg5ZWExZWY2MA==
  size: 32771159
