---
terracotta/terracotta-3.7.5.tar.gz:
  object_id: 3cb26400-f6f0-4fe2-be13-39cbfa1d9cfb
  sha: !binary |-
    N2Q5YTk3MWY2NDA5Y2MwMjExNDFjMjFmN2E1MWE0MjY0MWRhZjFhYw==
  size: 62254931
java/jre-7u4-linux-x64.tar.gz:
  object_id: f3491a15-7e56-4663-9f7f-127b8d10aa26
  sha: !binary |-
    N2I5Mjg3MzVkOWI0N2Q1YzRjNzEyMDY0MGIxOTMyMjAxMDlmNjJlMg==
  size: 32881501
